# Copyright (c) 2023 Andrea Ballestrazzi

name: Linux Build and Tests

on:
  push:
    branches-ignore:
      - master
      - develop
      - release

jobs:
  gcc-13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest

      - name: Configure compiler
        run: |
          sudo apt-get install -y g++-13
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 90
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 90
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-13 90


      - name: CMake configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: CMake build
        run: |
          cd build
          cmake --build . --config Release -j 18
